name: Bootstrap SNPRD IAC Roles

on:
  pull_request:
    branches:
    - main
    paths:
    - 'deployments/accounts/aws-mgmt/us-west-2/bootstrap-iac-roles-snprd/**'
    - '.github/workflows/bootstrap-snprd.yaml'
    - '.github/workflows/bootstrap-plan-apply-component.yaml'
  push:
    branches:
    - main
    paths:
    - 'deployments/accounts/aws-mgmt/us-west-2/bootstrap-iac-roles-snprd/**'
    - '.github/workflows/bootstrap-snprd.yaml'
    - '.github/workflows/bootstrap-plan-apply-component.yaml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
        - plan
        - apply
        default: plan

permissions:
  id-token: write
  contents: read

jobs:
  bootstrap-snprd:
    name: Bootstrap SNPRD IAC Roles
    uses: ./.github/workflows/bootstrap-plan-apply-component.yaml
    with:
      target_account: aws-shared-non-prod
      target_account_code: SNPRD
      target_account_id: "730335485168"
      region: us-west-2
      component: bootstrap-iac-roles-snprd
      repository_type: cicdsecurity
      force_action: ${{ github.event.inputs.action || '' }}
    secrets: inherit